version: '3.8'

services:
  # ASP.NET App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EmployeeImporter;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - employee-network

  # SQL Server Service 
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge

volumes:
  mssql-data: